#!/usr/bin/env sh

# projects
# one
type=$1

optimizeImage() {
    image=$1
    width=$2
    optimizedImage="${image/-0.jpg/-${width}.jpg}"
    echo "$width: $optimizedImage"
    magick "${image}" -format jpeg -sampling-factor 4:2:0 -strip -quality 80 -interlace JPEG -colorspace sRGB -resize "${width}"x "${optimizedImage}"
}

clean() {
  dir=$1
  width=$2
  find "${dir}" -name "*-${width}.jpg" -delete
}

optimizeProjects() {
  # projects
  dir="src/assets/images/project"
  # cleanup
  echo "Cleanup directory from autogenerated images [${dir}]"
  clean "${dir}" 400
  clean "${dir}" 1500
  # optimize
  images=( $(find -L "${dir}" -name "*-0.jpg") )
  for image in "${images[@]}"
  do
      echo "Optimize: ${image}"
      optimizeImage "${image}" 400
      optimizeImage "${image}" 1500
  done
}

# ./optimize-images.sh projects
if [ "${type}" == "projects" ]; then
    optimizeProjects
fi

if [ "${type}" == "one" ]; then
    magick "src/assets/images/${2}" -format jpeg -sampling-factor 4:2:0 -strip -quality 80 -interlace JPEG -colorspace sRGB "src/assets/images/${2}"
fi

#./optimize-images.sh one-width project/personal-exhibition-fragile/fragile-main.jpg 500
#./optimize-images.sh one-width project/shadows-of-unforgotten-ancestors/shadows-of-unforgotten-ancestors-main.jpg 500
#./optimize-images.sh one-width project/black-and-white/black-and-white-main.jpg 500
#./optimize-images.sh one-width project/feeling-and-living/feeling-and-living-main.jpg 500
#./optimize-images.sh one-width project/jazzman/jazzman-main.jpg 500
if [ "${type}" == "one-width" ]; then
    image="src/assets/images/${2}"
    width=$3
    optimizedImage="${image/.jpg/-${width}.jpg}"
    echo "Optimize ${image} to width ${width}"
    magick "${image}" -format jpeg -sampling-factor 4:2:0 -strip -quality 100 -interlace JPEG -colorspace sRGB -resize "${width}"x "${optimizedImage}"
fi
